name: "YAML Deep Merge"
description: "This action reads YAML configuration files, with support to variable interpolation"
author: "spekosolutions"
branding:
  icon: box
  color: blue
inputs:
  file-paths:
    description: "Config files"
    required: true
    default: ""
  key-path:
    description: "Key path to filter out in the yaml file"
    required: false
    default: ""
output:
  data:
    description: 'Data read from YAML file'
runs:
  using: "node20"
  main: 'dist/index.js'
