on: [ push, pull_request ]

jobs:
  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: using
        uses: ./
        with:
          config-files: |-
            ${{ github.workspace }}/action.yml
          # key-path: '["runs", "using"]'

      - name: Get read-yaml outputs
        run: |
          echo "${{ steps.using.outputs.data }}"